export const SET_CHARACTER = "SET_CHARACTER"
export const DELETE_CHARACTER = "DELETE_CHARACTER"
export const CLEAR_DATA = "CLEAR_DATA"
export const UPDATE_CHARACTER = "UPDATE_CHARACTER"
export const SET_ACHIEVEMENT = "SET_ACHIEVEMENT"
export const CLEAR_ACHIEVEMENT = "CLEAR_ACHIEVEMENT"
export const LOADING = "LOADING";
